//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisPlanner.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeoLocations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeoLocations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TennisPlanner.Core.Resources.GeoLocations", typeof(GeoLocations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,410429;48,838003.
        /// </summary>
        public static string TENNIS_Alain_Mimoun {
            get {
                return ResourceManager.GetString("TENNIS Alain Mimoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,386217;48,865839.
        /// </summary>
        public static string TENNIS_Amandiers {
            get {
                return ResourceManager.GetString("TENNIS Amandiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,319296;48,840803.
        /// </summary>
        public static string TENNIS_Atlantique {
            get {
                return ResourceManager.GetString("TENNIS Atlantique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,28114;48,883177.
        /// </summary>
        public static string TENNIS_Aurelle_de_Paladines {
            get {
                return ResourceManager.GetString("TENNIS Aurelle de Paladines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,342054;48,899487.
        /// </summary>
        public static string TENNIS_Bertrand_Dauvin {
            get {
                return ResourceManager.GetString("TENNIS Bertrand Dauvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,418141;48,909202.
        /// </summary>
        public static string TENNIS_Bobigny {
            get {
                return ResourceManager.GetString("TENNIS Bobigny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,380032;48,851382.
        /// </summary>
        public static string TENNIS_Candie {
            get {
                return ResourceManager.GetString("TENNIS Candie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,412784;48,84314.
        /// </summary>
        public static string TENNIS_Carnot {
            get {
                return ResourceManager.GetString("TENNIS Carnot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,361998;48,830494.
        /// </summary>
        public static string TENNIS_Château_des_Rentiers {
            get {
                return ResourceManager.GetString("TENNIS Château des Rentiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,348605;48,833351.
        /// </summary>
        public static string TENNIS_Cordelières {
            get {
                return ResourceManager.GetString("TENNIS Cordelières", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,292427;48,889471.
        /// </summary>
        public static string TENNIS_Courcelles {
            get {
                return ResourceManager.GetString("TENNIS Courcelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,294626;48,842454.
        /// </summary>
        public static string TENNIS_Croix_Nivert {
            get {
                return ResourceManager.GetString("TENNIS Croix Nivert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,412285;48,855507.
        /// </summary>
        public static string TENNIS_Docteurs_Déjerine {
            get {
                return ResourceManager.GetString("TENNIS Docteurs Déjerine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,366279;48,83317.
        /// </summary>
        public static string TENNIS_Dunois {
            get {
                return ResourceManager.GetString("TENNIS Dunois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,377022;48,880595.
        /// </summary>
        public static string TENNIS_Edouard_Pailleron {
            get {
                return ResourceManager.GetString("TENNIS Edouard Pailleron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,328651;48,821157.
        /// </summary>
        public static string TENNIS_Elisabeth {
            get {
                return ResourceManager.GetString("TENNIS Elisabeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,366051;48,818907.
        /// </summary>
        public static string TENNIS_Georges_Carpentier {
            get {
                return ResourceManager.GetString("TENNIS Georges Carpentier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,272121;48,867523.
        /// </summary>
        public static string TENNIS_Henry_de_Montherlant {
            get {
                return ResourceManager.GetString("TENNIS Henry de Montherlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,379872;48,875154.
        /// </summary>
        public static string TENNIS_Jandelle {
            get {
                return ResourceManager.GetString("TENNIS Jandelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,334439;48,89469.
        /// </summary>
        public static string TENNIS_Jesse_Owens {
            get {
                return ResourceManager.GetString("TENNIS Jesse Owens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,397736;48,893203.
        /// </summary>
        public static string TENNIS_Jules_Ladoumègue {
            get {
                return ResourceManager.GetString("TENNIS Jules Ladoumègue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,451513;48,829859.
        /// </summary>
        public static string TENNIS_La_Faluère {
            get {
                return ResourceManager.GetString("TENNIS La Faluère", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,399334;48,832165.
        /// </summary>
        public static string TENNIS_Léo_Lagrange {
            get {
                return ResourceManager.GetString("TENNIS Léo Lagrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,411646;48,859198.
        /// </summary>
        public static string TENNIS_Louis_Lumière {
            get {
                return ResourceManager.GetString("TENNIS Louis Lumière", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,325251;48,899125.
        /// </summary>
        public static string TENNIS_Max_Rousié {
            get {
                return ResourceManager.GetString("TENNIS Max Rousié", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,364135;48,827801.
        /// </summary>
        public static string TENNIS_Moureu___Baudricourt {
            get {
                return ResourceManager.GetString("TENNIS Moureu - Baudricourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,363531;48,853664.
        /// </summary>
        public static string TENNIS_NEUVE_SAINT_PIERRE {
            get {
                return ResourceManager.GetString("TENNIS NEUVE SAINT PIERRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,264491;48,837317.
        /// </summary>
        public static string TENNIS_Niox {
            get {
                return ResourceManager.GetString("TENNIS Niox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,305045;48,838732.
        /// </summary>
        public static string TENNIS_Paul_Barruel {
            get {
                return ResourceManager.GetString("TENNIS Paul Barruel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,390992;48,856693.
        /// </summary>
        public static string TENNIS_Philippe_Auguste {
            get {
                return ResourceManager.GetString("TENNIS Philippe Auguste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,351992;48,899686.
        /// </summary>
        public static string TENNIS_Poissonniers {
            get {
                return ResourceManager.GetString("TENNIS Poissonniers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,357496;48,839815.
        /// </summary>
        public static string TENNIS_Poliveau {
            get {
                return ResourceManager.GetString("TENNIS Poliveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,411131;48,862341.
        /// </summary>
        public static string TENNIS_Porte_de_Bagnolet {
            get {
                return ResourceManager.GetString("TENNIS Porte de Bagnolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,353835;48,820265.
        /// </summary>
        public static string TENNIS_Poterne_des_Peupliers {
            get {
                return ResourceManager.GetString("TENNIS Poterne des Peupliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,296156;48,888725.
        /// </summary>
        public static string TENNIS_Reims___Asnières {
            get {
                return ResourceManager.GetString("TENNIS Reims - Asnières", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,284871;48,848888.
        /// </summary>
        public static string TENNIS_René_et_André_Mourlon {
            get {
                return ResourceManager.GetString("TENNIS René et André Mourlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,300417;48,826634.
        /// </summary>
        public static string TENNIS_Rigoulot___La_Plaine {
            get {
                return ResourceManager.GetString("TENNIS Rigoulot - La Plaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,30205;48,843953.
        /// </summary>
        public static string TENNIS_Sablonnière {
            get {
                return ResourceManager.GetString("TENNIS Sablonnière", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,398788;48,889602.
        /// </summary>
        public static string TENNIS_Sept_arpents {
            get {
                return ResourceManager.GetString("TENNIS Sept arpents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,276576;48,833071.
        /// </summary>
        public static string TENNIS_Suzanne_Lenglen {
            get {
                return ResourceManager.GetString("TENNIS Suzanne Lenglen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,373838;48,853895.
        /// </summary>
        public static string TENNIS_Thiéré {
            get {
                return ResourceManager.GetString("TENNIS Thiéré", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2,345022;48,877967.
        /// </summary>
        public static string TENNIS_Valeyre {
            get {
                return ResourceManager.GetString("TENNIS Valeyre", resourceCulture);
            }
        }
    }
}
