//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisPlanner.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TennisPlanner.Core.Resources.Locations", typeof(Locations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 15 rue de la Nouvelle Calédonie 75012.
        /// </summary>
        internal static string TENNIS_Alain_Mimoun {
            get {
                return ResourceManager.GetString("TENNIS Alain Mimoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8 rue Louis Delgrès.
        /// </summary>
        internal static string TENNIS_Amandiers {
            get {
                return ResourceManager.GetString("TENNIS Amandiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 25 allée du Capitaine Dronne - Dalle Montparnasse porche ouest 75015.
        /// </summary>
        internal static string TENNIS_Atlantique {
            get {
                return ResourceManager.GetString("TENNIS Atlantique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 10, rue Parmentier 92200.
        /// </summary>
        internal static string TENNIS_Aurelle_de_Paladines {
            get {
                return ResourceManager.GetString("TENNIS Aurelle de Paladines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 12 rue René Binet 75018.
        /// </summary>
        internal static string TENNIS_Bertrand_Dauvin {
            get {
                return ResourceManager.GetString("TENNIS Bertrand Dauvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 40 - 102, avenue de la Division Leclerc 93000.
        /// </summary>
        internal static string TENNIS_Bobigny {
            get {
                return ResourceManager.GetString("TENNIS Bobigny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 11 rue Candie 75011.
        /// </summary>
        internal static string TENNIS_Candie {
            get {
                return ResourceManager.GetString("TENNIS Candie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 26 boulevard Carnot 75012.
        /// </summary>
        internal static string TENNIS_Carnot {
            get {
                return ResourceManager.GetString("TENNIS Carnot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 184 rue du Château des Rentiers 75013.
        /// </summary>
        internal static string TENNIS_Château_des_Rentiers {
            get {
                return ResourceManager.GetString("TENNIS Château des Rentiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 35 rue des Cordelières 75013.
        /// </summary>
        internal static string TENNIS_Cordelières {
            get {
                return ResourceManager.GetString("TENNIS Cordelières", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 211, rue de Courcelles 75017.
        /// </summary>
        internal static string TENNIS_Courcelles {
            get {
                return ResourceManager.GetString("TENNIS Courcelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 107 rue de la Croix Nivert 75015.
        /// </summary>
        internal static string TENNIS_Croix_Nivert {
            get {
                return ResourceManager.GetString("TENNIS Croix Nivert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 32-36 rue des Docteurs Augusta et Jules Déjerine 75020.
        /// </summary>
        internal static string TENNIS_Docteurs_Déjerine {
            get {
                return ResourceManager.GetString("TENNIS Docteurs Déjerine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 70 rue Dunois 75013.
        /// </summary>
        internal static string TENNIS_Dunois {
            get {
                return ResourceManager.GetString("TENNIS Dunois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 24 rue Edouard Pailleron 75019.
        /// </summary>
        internal static string TENNIS_Edouard_Pailleron {
            get {
                return ResourceManager.GetString("TENNIS Edouard Pailleron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7 avenue Paul Appell 75014.
        /// </summary>
        internal static string TENNIS_Elisabeth {
            get {
                return ResourceManager.GetString("TENNIS Elisabeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5 Place de Port au Prince 75013.
        /// </summary>
        internal static string TENNIS_Georges_Carpentier {
            get {
                return ResourceManager.GetString("TENNIS Georges Carpentier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 30-32 Boulevard Lannes 75016.
        /// </summary>
        internal static string TENNIS_Henry_de_Montherlant {
            get {
                return ResourceManager.GetString("TENNIS Henry de Montherlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 15-17 cité Jandelle 75019.
        /// </summary>
        internal static string TENNIS_Jandelle {
            get {
                return ResourceManager.GetString("TENNIS Jandelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 172 rue Championnet 75018.
        /// </summary>
        internal static string TENNIS_Jesse_Owens {
            get {
                return ResourceManager.GetString("TENNIS Jesse Owens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 39 rue des Petits Ponts 75019.
        /// </summary>
        internal static string TENNIS_Jules_Ladoumègue {
            get {
                return ResourceManager.GetString("TENNIS Jules Ladoumègue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à route de la Pyramide 75012.
        /// </summary>
        internal static string TENNIS_La_Faluère {
            get {
                return ResourceManager.GetString("TENNIS La Faluère", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 68, boulevard Poniatowski 75012.
        /// </summary>
        internal static string TENNIS_Léo_Lagrange {
            get {
                return ResourceManager.GetString("TENNIS Léo Lagrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 30 rue Louis Lumière 75020.
        /// </summary>
        internal static string TENNIS_Louis_Lumière {
            get {
                return ResourceManager.GetString("TENNIS Louis Lumière", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 28, rue André Bréchet 75017.
        /// </summary>
        internal static string TENNIS_Max_Rousié {
            get {
                return ResourceManager.GetString("TENNIS Max Rousié", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 17 avenue Edison 75013.
        /// </summary>
        internal static string TENNIS_Moureu___Baudricourt {
            get {
                return ResourceManager.GetString("TENNIS Moureu - Baudricourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5 - 7 rue Neuve-Saint-Pierre 75004.
        /// </summary>
        internal static string TENNIS_NEUVE_SAINT_PIERRE {
            get {
                return ResourceManager.GetString("TENNIS NEUVE SAINT PIERRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 12 quai Saint-Exupéry 75016.
        /// </summary>
        internal static string TENNIS_Niox {
            get {
                return ResourceManager.GetString("TENNIS Niox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 24 rue Paul Barruel 75015.
        /// </summary>
        internal static string TENNIS_Paul_Barruel {
            get {
                return ResourceManager.GetString("TENNIS Paul Barruel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 108 avenue Philippe Auguste 75011.
        /// </summary>
        internal static string TENNIS_Philippe_Auguste {
            get {
                return ResourceManager.GetString("TENNIS Philippe Auguste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2 rue Jean Cocteau 75018.
        /// </summary>
        internal static string TENNIS_Poissonniers {
            get {
                return ResourceManager.GetString("TENNIS Poissonniers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 39BIS RUE DE POLIVEAU 75005.
        /// </summary>
        internal static string TENNIS_Poliveau {
            get {
                return ResourceManager.GetString("TENNIS Poliveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 72 rue Louis Lumière 75020.
        /// </summary>
        internal static string TENNIS_Porte_de_Bagnolet {
            get {
                return ResourceManager.GetString("TENNIS Porte de Bagnolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 17 rue Max Jacob 75013.
        /// </summary>
        internal static string TENNIS_Poterne_des_Peupliers {
            get {
                return ResourceManager.GetString("TENNIS Poterne des Peupliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 34, boulevard de Reims 75017.
        /// </summary>
        internal static string TENNIS_Reims___Asnières {
            get {
                return ResourceManager.GetString("TENNIS Reims - Asnières", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 19 rue Gaston de Caillavet 75015.
        /// </summary>
        internal static string TENNIS_René_et_André_Mourlon {
            get {
                return ResourceManager.GetString("TENNIS René et André Mourlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 18 avenue de la Porte de Brancion 75015.
        /// </summary>
        internal static string TENNIS_Rigoulot___La_Plaine {
            get {
                return ResourceManager.GetString("TENNIS Rigoulot - La Plaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 62 rue Cambronne 75015.
        /// </summary>
        internal static string TENNIS_Sablonnière {
            get {
                return ResourceManager.GetString("TENNIS Sablonnière", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 9 rue des Sept Arpents 75019.
        /// </summary>
        internal static string TENNIS_Sept_arpents {
            get {
                return ResourceManager.GetString("TENNIS Sept arpents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2 rue Louis Armand 75015.
        /// </summary>
        internal static string TENNIS_Suzanne_Lenglen {
            get {
                return ResourceManager.GetString("TENNIS Suzanne Lenglen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 9t-11 passage Thiéré 75011.
        /// </summary>
        internal static string TENNIS_Thiéré {
            get {
                return ResourceManager.GetString("TENNIS Thiéré", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 24 rue de Rochechouart 75009.
        /// </summary>
        internal static string TENNIS_Valeyre {
            get {
                return ResourceManager.GetString("TENNIS Valeyre", resourceCulture);
            }
        }
    }
}
